name: Nix package build

on: [push]

jobs:
  build:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, id: linux }
          - { os: macos-latest, id: mac }

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build and check the packages
        run: nix flake check --max-jobs 1 -L
